app/urls.py
from django.urls import path
from . import views

app_name ='app'
urlpatterns = [
    path('', views.index, name='index',),
    path('<int:memo_id>', views.detail, name='detail',),
    path('post', views.post, name='post'),
    path('about', views.about, name='about'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name='delete_memo')
]

memo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    title = models.CharField(max_length=30)
    text = models.TextField(blank=True)
    created_datatime = models.DateTimeField(auto_now_add=True)
    updated_datatime = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'メモ'
        verbose_name_plural = 'メモ'
    
    

app/forms.py
from django.forms import ModelForm
from .models import Memo

class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

app/views.py
from django.shortcuts import render,redirect
from .models import Memo
from .forms import MemoForm
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    memos = Memo.objects.all().order_by("-updated_datatime")
    return render(request, 'app/index.html', { 'memos': memos })

def detail(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    return render(request, 'app/detail.html',{'memo':memo})

def post (request):
    if request.method == "POST":
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:   
        form = MemoForm
    return render(request, 'app/post.html', {'form': form })

def about (request):
    return render(request, 'app/about.html')

@require_POST
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    memo.delete()
    return redirect('app:index')

app/templates/app/about.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/css/uikit.min.css" />

<!--Google fonts-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi&family=Montserrat:wght@100&display=swap" rel="stylesheet">

<!--Custom CSS-->
<link rel="stylesheet" href="{% static 'app/style.css' %}">

    <title>メモ with Django</title>
</head>
<body>
    <!--Nav-->
    <nav class="uk-navbar-container uk-margin" uk-navbar>
        <div class="uk-navbar-left">
    
            <a class="uk-navbar-item uk-logo" href="#">メモ with Django</a>
    
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'app:index' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: home"></span>
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:post' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: pencil"></span>
                        Post
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:about' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: info"></span>
                        About this site
                    </a>
                </li>
            </ul>  
        </div>
    </nav>
<section class="about">
    <div class="uk-section uk-section-muted">
        <div class="uk-container">
    
            <h3>About this site</h3>
    
            <div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
                <div>
                    <p>Django学習</p>
                </div>
                <div>
                    <p></p>
                </div>
                <div>
                    <p></p>
                </div>
            </div>
    
        </div>
    </div>
</section>


<!-- UIkit JS -->
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit-icons.min.js"></script>
</body>
</html>

app/templates/app/detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/css/uikit.min.css" />
</head>
<body>
     <!--Nav-->
     <nav class="uk-navbar-container uk-margin" uk-navbar>
        <div class="uk-navbar-left">
    
            <a class="uk-navbar-item uk-logo" href="#">メモ with Django</a>
    
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'app:index' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: home"></span>
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:post' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: pencil"></span>
                        Post
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:about' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: info"></span>
                        About this site
                    </a>
                </li>
            </ul>  
        </div>
    </nav>
    <section class="detail">
        <div class="uk-section uk-section-muted">
            <div class="uk-container">
                <div>
                    <a href="{% url 'app:index' %}">ホームに戻る</a>
                  </div>
        
                <h3>{{ memo.title }}</h3>
        
                <div class="uk-grid-match uk-child-width-1-3@m" uk-grid>
                    <div>
                        {{ memo.text | linebreaks | urlize }}
                    </div>
                </div>
            </div>
        </div>
        <form method="post" action="{% url 'app:delete_memo' memo.pk %}">{% csrf_token %}
            <button class="uk-button uk-button-secondary" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
          </form>
    </section>
<!-- UIkit JS -->
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit-icons.min.js"></script>
</body>
</html>

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/css/uikit.min.css" />

<!--Google fonts-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi&family=Montserrat:wght@100&display=swap" rel="stylesheet">

<!--Custom CSS-->
<link rel="stylesheet" href="{% static 'app/style.css' %}">

    <title>メモ with Django</title>
</head>
<body>
    <!--Nav-->
    <nav class="uk-navbar-container uk-margin" uk-navbar>
        <div class="uk-navbar-left">
    
            <a class="uk-navbar-item uk-logo" href="#">メモ with Django</a>
    
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'app:index' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: home"></span>
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:post' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: pencil"></span>
                        Post
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:about' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: info"></span>
                        About this site
                    </a>
                </li>
            </ul>  
        </div>
    </nav>
<!--Memo Contents-->
<section class="memo">
    {% for memo in memos %}
    <div class="uk-card uk-card-default uk-card-body uk-width-1-2@s">
        <a href="{% url 'app:detail' memo.id %}" class="memo-title">
            <div>
              {{ memo }}
              <span>{{ memo.updated_datatime }}</span>
            </div>
          </a>
    </div>
    </a>
    {% endfor %}
</section>

<!-- UIkit JS -->
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit-icons.min.js"></script>
</body>
</html>

app/templates/app/post.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- UIkit CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/css/uikit.min.css" />

<!--Google fonts-->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kaisei+HarunoUmi&family=Montserrat:wght@100&display=swap" rel="stylesheet">

<!--Custom CSS-->
<link rel="stylesheet" href="{% static 'app/style.css' %}">

    <title>メモ with Django</title>
</head>
<body>
    <!--Nav-->
    <nav class="uk-navbar-container uk-margin" uk-navbar>
        <div class="uk-navbar-left">
    
            <a class="uk-navbar-item uk-logo" href="#">メモ with Django</a>
    
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'app:index' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: home"></span>
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:post' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: pencil"></span>
                        Post
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:about' %}">
                        <span class="uk-icon uk-margin-small-right" uk-icon="icon: info"></span>
                        About this site
                    </a>
                </li>
            </ul>  
        </div>
    </nav>
    <!--Post Form-->
<section id="form">
    <form action="{% url 'app:post' %}" method="POST">{% csrf_token %}
        {{form.as_p}}
        <fieldset class="uk-fieldset">
            <button type="submit" class="uk-button uk-button-primary">Submit</button>
        </fieldset>
    </form>
    
</section>


<!-- UIkit JS -->
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uikit@3.7.3/dist/js/uikit-icons.min.js"></script>
</body>
</html>